### PR TITLE
Replace defaultProps with default parameters across the project

### PR DESCRIPTION
**Pull request by julekgwa**

### CODE REVIEW

**Comment by julekgwa** [comment]
Fixes #149 and #148

**Review by vishnu-krishna — APPROVED** [review]

**Comment by Inkvi** [comment]
@julekgwa can you merge this PR?

**Comment by jaslam-ca** [comment]
@julekgwa can you merge this PR and create a new release?

**Comment by julekgwa** [comment]
I don't have access to merge the PR.

**Comment by jfilter** [comment]
Thanks @julekgwa! I will release a new version.

**Pull request merged**
