### PR TITLE
Fix bugs in RTL support

### PR DESCRIPTION
**Pull request by dalwadani**
This PR fix the following issues in RTL:
- Calculating last page in Pagination
- goNext in RTL should move to the correct index

### CODE REVIEW

**Comment by jfilter** [comment]
Thanks!

**Comment by yossipik** [comment]
It seems that this fix https://github.com/jfilter/react-native-onboarding-swiper/pull/85/commits/206f104608b6faac5eb5da389c0ca94672609b4b is appropriate only for iOS.
On Android it causes the 'done' button to be shown on the first page and the 'next' is shown on the last page.
Can you please check that?

**Comment by jfilter** [comment]
Hey @yossipik, thanks for pointing out the bug. I fixed it in `1.1.3`. I'm not 100% sure why iOS & Android need special treatment here. But it should be fine now.

**Comment by yossipik** [comment]
Great. Thanks!

> Hey @yossipik, thanks for pointing out the bug. I fixed it in `1.1.3`. I'm not 100% sure why iOS & Android need special treatment here. But it should be fine now.

**Comment by yossipik** [comment]
Hi @jfilter I'm afraid the fix is not complete - need to make the same change here as well https://github.com/jfilter/react-native-onboarding-swiper/pull/85/commits/22cceab9cac8a8f7593d5780d43f7573c99ff66d or otherwise you get an out of index exception

**Comment by jfilter** [comment]
You're right, fixed in `1.1.4`.

**Pull request merged**
